### ISSUE TITLE
It doesn't seem to work with HL

### ISSUE THREAD

**Issue by jeremyfa** [jeremyfa/interpret#3]
Interpret macro is failing to load Std type when using HL target.

That should probably not be too hard to fix, but needs to be tested.

**Comment by kiroukou** [comment]
Hey,
I'm currently have a try with HL and it doesn't seems to work..
BUT, I do not get any error or anything. 
How should I debug the application?

**Comment by jeremyfa** [comment]
Although this issue is still open, I managed to get it to work with HL. Did you checkout the sample in the repo?

Also, if you want to perform live reload, you need to add these defines in your hxml:

```
-D interpretable
-D interpret_watch
```

**Comment by kiroukou** [comment]
Well, I did follow the instructions you put in the readme file.  Mostly: 
```
#if interpretable
		Env.configureInterpretableEnv = function(env) {
			env.addDefaultModules();
			env.addModule('level.struct.GreenHouse', DynamicModule.fromStatic(level.struct.GreenHouse));
		};
		LiveReload.start();
		#end

....

               #if interpretable
		LiveReload.tick(dt);
		#end 
```
 My class 'GreenHouse' does implements Interpretable and the method I'm expecting to live edit has the @interpret meta in it.


HXML:
```
...
-D interpretable
-D interpret_watch
#--interp
-main LdApp
-hl bin/ld.hl
```

But now I'm wondering how the glue is made with the hscript interpreter (how to you expose types to it). That may be causing the lack of live reloading I guess (but no error popping from a macro or anything so far).

Anyhow, if you have any idea to check if the hscripting is correctly generated and after that how to debug, I'm looking forward to them :)

**Comment by jeremyfa** [comment]
You need to ensure LiveReload.tick() is called regularly (with a valid and non zero delta value). Is this the case?

**Comment by kiroukou** [comment]
yes that is the case.  
I've managed to get your sample to work btw.
One possible issue can be the hscript lib version I'm using.  I'm experimenting with thhat at the moment.

**Comment by jeremyfa** [comment]
Maybe, not sure what is happening but yes, the samples are a good start to make things work as the library is pretty rough for now.

Closing this as HL is now working at least as well as other supported targets.
